# IMPORTANT!!! 
#   Ensure that the min_us and max_us are properly adjusted for to account for the found neutral offsets
#   It is not automatic!

arm_motors:
  - id: 1
    topic: "/arm/motor_base_yaw"

  - id: 2
    topic: "/arm/motor_base_pitch"

  - id: 3
    topic: "/arm/motor_elbow_pitch"

  - id: 4
    topic: "/arm/motor_wrist_yaw"

  - id: 5
    topic: "/arm/motor_wrist_pitch"

  - id: 6
    topic: "/arm/motor_claw"
