# Position and direction of each thruster on the ROV
# - Direction is a unit vector indicating the force vector applied to the ROV when the motor is active
# - Position is the location of the thruster relative to the ROV's center of mass, in meters


# IMPORTANT!!! 
#   Ensure that the min_us and max_us are properly adjusted for to account for the found neutral offsets
#   It is not automatic!

thrusters:
  - id: 1
    name: front_left_lateral
    min_us: 1130
    max_us: 1930
    neutral_us: 1530
    channel: 7
    topic: /thruster/thruster_fll

  - id: 2
    name: front_right_lateral
    min_us: 1130
    max_us: 1930
    neutral_us: 1530
    channel: 4
    topic: /thruster/thruster_frl

  - id: 3
    name: rear_left_lateral
    min_us: 1130
    max_us: 1930
    neutral_us: 1530
    channel: 1
    topic: /thruster/thruster_rll

  - id: 4
    name: rear_right_lateral
    min_us: 1130
    max_us: 1930
    neutral_us: 1530
    channel: 3
    topic: /thruster/thruster_rrl

  - id: 5
    name: front_left_vertical
    min_us: 1130
    max_us: 1930
    neutral_us: 1530
    channel: 5
    topic: /thruster/thruster_flv

  - id: 6
    name: front_right_vertical
    min_us: 1130
    max_us: 1930
    neutral_us: 1530
    channel: 6
    topic: /thruster/thruster_frv

  - id: 7
    name: rear_left_vertical
    min_us: 1130
    max_us: 1930
    neutral_us: 1530
    channel: 0
    topic: /thruster/thruster_rlv

  - id: 8
    name: rear_right_vertical
    min_us: 1130
    max_us: 1930
    neutral_us: 1530
    channel: 2
    topic: /thruster/thruster_rrv
